# Generated by Django 4.2.5 on 2023-09-16 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Nested", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="customers_model",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=200)),
                ("lastname", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="orders_model",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("product", models.CharField(max_length=200)),
                ("quantity", models.IntegerField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="Nested.customers_model",
                    ),
                ),
            ],
        ),
    ]
