# Generated by Django 4.2.5 on 2023-09-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="students",
            old_name="name",
            new_name="Username",
        ),
    ]
