# Generated by Django 4.2.5 on 2023-09-16 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_name_students_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="students",
            old_name="Username",
            new_name="username",
        ),
    ]
