services:
  db:
    image: postgres:15.2
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgreSql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - 5051:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com 
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - pgadmin:/var/lib/pgadmin/  
volumes:
  postgres_data:
  pgadmin:
