# Generated by Django 4.2.5 on 2023-09-23 04:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('traditional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('files', models.FileField(upload_to='')),
            ],
        ),
    ]
