# Generated by Django 4.2.5 on 2023-09-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="user_model",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=200, unique=True)),
                ("salary", models.DecimalField(decimal_places=3, max_digits=13)),
            ],
        ),
    ]
